Improve build argument parsing

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -99,11 +99,22 @@ runs:
             docker_tag_args="$docker_tag_args -t $2/$image:$t"
           done
 
-          IFS=',' read -d '' -ra ARRAY <<< "$buildArgs"
+          IFS=';'
+          ARGS_ARRAY=($buildArgs)
           ADDITIONAL_BUILD_ARGS=""
-          for i in "${ARRAY[@]}"
+          for i in "${ARGS_ARRAY[@]}"
           do
-            ADDITIONAL_BUILD_ARGS+="--build-arg $i "
+            if [[ "$i" =~ ([a-Z0-9_]*)=(.*) ]]; then
+              if [[ ${BASH_REMATCH[1]} && ${BASH_REMATCH[2]} ]]; then
+                ADDITIONAL_BUILD_ARGS+="--build-arg ${BASH_REMATCH[0]} "
+              else
+                echo "Invalid buildArgs format: ${i}"
+                exit 1
+              fi
+            else
+              echo "Invalid buildArgs format: ${i}"
+              exit 1
+            fi
           done
 
           docker build --build-arg version=${tag} ${ADDITIONAL_BUILD_ARGS} -f Dockerfile $docker_tag_args .
